var classes = [
    {
        "name": "App\\Config\\Config",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "initDatabase",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "isDatabaseAvailable",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 3,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "App\\Database\\Database",
            "App\\Database\\Database"
        ],
        "parents": [],
        "implements": [],
        "lcom": 2,
        "length": 21,
        "vocabulary": 20,
        "volume": 90.76,
        "difficulty": 1,
        "effort": 90.76,
        "level": 1,
        "bugs": 0.03,
        "time": 5,
        "intelligentContent": 90.76,
        "number_operators": 3,
        "number_operands": 18,
        "number_operators_unique": 2,
        "number_operands_unique": 18,
        "cloc": 7,
        "loc": 36,
        "lloc": 29,
        "mi": 85.68,
        "mIwoC": 54.12,
        "commentWeight": 31.56,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 4,
        "relativeDataComplexity": 0.67,
        "relativeSystemComplexity": 4.67,
        "totalStructuralComplexity": 8,
        "totalDataComplexity": 1.33,
        "totalSystemComplexity": 9.33,
        "package": "App\\Config\\",
        "pageRank": 0.08,
        "afferentCoupling": 3,
        "efferentCoupling": 1,
        "instability": 0.25,
        "violations": {}
    },
    {
        "name": "App\\Controllers\\AboutController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "get",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "App\\Views\\AboutTemplate"
        ],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 0,
        "vocabulary": 0,
        "volume": 0,
        "difficulty": 0,
        "effort": 0,
        "level": 0,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 0,
        "number_operators": 0,
        "number_operands": 0,
        "number_operators_unique": 0,
        "number_operands_unique": 0,
        "cloc": 0,
        "loc": 8,
        "lloc": 8,
        "mi": 171,
        "mIwoC": 171,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 0.5,
        "relativeSystemComplexity": 1.5,
        "totalStructuralComplexity": 1,
        "totalDataComplexity": 0.5,
        "totalSystemComplexity": 1.5,
        "package": "App\\Controllers\\",
        "pageRank": 0.01,
        "afferentCoupling": 1,
        "efferentCoupling": 1,
        "instability": 0.5,
        "violations": {}
    },
    {
        "name": "App\\Controllers\\AdminController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "checkAdmin",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "index",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "orders",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "users",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getStats",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getOrders",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "apiStats",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "apiOrders",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "apiUsers",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "logs",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "apiLogs",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "apiClearLogs",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "catalog",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "apiProducts",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "apiCreateProduct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "apiUpdateProduct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "apiDeleteProduct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 18,
        "nbMethods": 18,
        "nbMethodsPrivate": 3,
        "nbMethodsPublic": 15,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 69,
        "ccn": 52,
        "ccnMethodMax": 11,
        "externals": [
            "App\\Models\\User",
            "App\\Models\\Product",
            "App\\Views\\AdminTemplate",
            "App\\Views\\AdminTemplate",
            "App\\Views\\AdminTemplate",
            "App\\Models\\Logger",
            "App\\Views\\AdminTemplate",
            "App\\Models\\Logger",
            "App\\Models\\Logger",
            "App\\Views\\AdminTemplate"
        ],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 400,
        "vocabulary": 75,
        "volume": 2491.53,
        "difficulty": 26.19,
        "effort": 65254.29,
        "level": 0.04,
        "bugs": 0.83,
        "time": 3625,
        "intelligentContent": 95.13,
        "number_operators": 125,
        "number_operands": 275,
        "number_operators_unique": 12,
        "number_operands_unique": 63,
        "cloc": 57,
        "loc": 282,
        "lloc": 225,
        "mi": 49.99,
        "mIwoC": 17.91,
        "commentWeight": 32.08,
        "kanDefect": 2.29,
        "relativeStructuralComplexity": 256,
        "relativeDataComplexity": 1.83,
        "relativeSystemComplexity": 257.83,
        "totalStructuralComplexity": 4608,
        "totalDataComplexity": 32.94,
        "totalSystemComplexity": 4640.94,
        "package": "App\\Controllers\\",
        "pageRank": 0.01,
        "afferentCoupling": 1,
        "efferentCoupling": 4,
        "instability": 0.8,
        "violations": {}
    },
    {
        "name": "App\\Controllers\\AuthController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "register",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "verify",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "resendCode",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "login",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "logout",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getCurrentUser",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "apiRegister",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "apiLogin",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "apiVerify",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "apiResend",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "apiLogout",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "apiGetCurrent",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 13,
        "nbMethods": 13,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 13,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 89,
        "ccn": 77,
        "ccnMethodMax": 13,
        "externals": [
            "App\\Models\\User",
            "App\\Models\\EmailSender",
            "App\\Views\\AuthTemplate",
            "App\\Views\\AuthTemplate",
            "App\\Models\\EmailSender",
            "App\\Views\\AuthTemplate",
            "App\\Models\\EmailSender",
            "App\\Models\\EmailSender"
        ],
        "parents": [],
        "implements": [],
        "lcom": 4,
        "length": 678,
        "vocabulary": 64,
        "volume": 4068,
        "difficulty": 39.44,
        "effort": 160427.13,
        "level": 0.03,
        "bugs": 1.36,
        "time": 8913,
        "intelligentContent": 103.15,
        "number_operators": 196,
        "number_operands": 482,
        "number_operators_unique": 9,
        "number_operands_unique": 55,
        "cloc": 57,
        "loc": 353,
        "lloc": 296,
        "mi": 39.62,
        "mIwoC": 10.46,
        "commentWeight": 29.15,
        "kanDefect": 2.81,
        "relativeStructuralComplexity": 144,
        "relativeDataComplexity": 1.92,
        "relativeSystemComplexity": 145.92,
        "totalStructuralComplexity": 1872,
        "totalDataComplexity": 25,
        "totalSystemComplexity": 1897,
        "package": "App\\Controllers\\",
        "pageRank": 0.01,
        "afferentCoupling": 1,
        "efferentCoupling": 3,
        "instability": 0.75,
        "violations": {}
    },
    {
        "name": "App\\Controllers\\CartController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "get",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "order",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "add",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "update",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "remove",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "clear",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "updateStatus",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 8,
        "nbMethods": 8,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 8,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 36,
        "ccn": 29,
        "ccnMethodMax": 11,
        "externals": [
            "App\\Views\\CartTemplate",
            "App\\Models\\Cart",
            "App\\Models\\Cart",
            "App\\Models\\EmailSender",
            "App\\Models\\Cart",
            "App\\Models\\Cart",
            "App\\Models\\Cart",
            "App\\Models\\Cart",
            "App\\Models\\Cart",
            "App\\Models\\Cart",
            "App\\Models\\Cart",
            "App\\Models\\Cart",
            "App\\Models\\Cart",
            "App\\Models\\Cart",
            "App\\Models\\Cart"
        ],
        "parents": [],
        "implements": [],
        "lcom": 8,
        "length": 285,
        "vocabulary": 64,
        "volume": 1710,
        "difficulty": 17.26,
        "effort": 29520.82,
        "level": 0.06,
        "bugs": 0.57,
        "time": 1640,
        "intelligentContent": 99.05,
        "number_operators": 74,
        "number_operands": 211,
        "number_operators_unique": 9,
        "number_operands_unique": 55,
        "cloc": 39,
        "loc": 164,
        "lloc": 125,
        "mi": 62,
        "mIwoC": 27.72,
        "commentWeight": 34.28,
        "kanDefect": 1.8,
        "relativeStructuralComplexity": 100,
        "relativeDataComplexity": 1.6,
        "relativeSystemComplexity": 101.6,
        "totalStructuralComplexity": 800,
        "totalDataComplexity": 12.82,
        "totalSystemComplexity": 812.82,
        "package": "App\\Controllers\\",
        "pageRank": 0.01,
        "afferentCoupling": 1,
        "efferentCoupling": 3,
        "instability": 0.75,
        "violations": {}
    },
    {
        "name": "App\\Controllers\\CatalogController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "get",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "filterProducts",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 1,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 10,
        "ccn": 9,
        "ccnMethodMax": 7,
        "externals": [
            "App\\Models\\Product",
            "App\\Views\\CatalogTemplate"
        ],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 55,
        "vocabulary": 18,
        "volume": 229.35,
        "difficulty": 7.12,
        "effort": 1631.88,
        "level": 0.14,
        "bugs": 0.08,
        "time": 91,
        "intelligentContent": 32.23,
        "number_operators": 18,
        "number_operands": 37,
        "number_operators_unique": 5,
        "number_operands_unique": 13,
        "cloc": 1,
        "loc": 29,
        "lloc": 28,
        "mi": 64.88,
        "mIwoC": 50.69,
        "commentWeight": 14.19,
        "kanDefect": 0.52,
        "relativeStructuralComplexity": 9,
        "relativeDataComplexity": 0.75,
        "relativeSystemComplexity": 9.75,
        "totalStructuralComplexity": 18,
        "totalDataComplexity": 1.5,
        "totalSystemComplexity": 19.5,
        "package": "App\\Controllers\\",
        "pageRank": 0.01,
        "afferentCoupling": 1,
        "efferentCoupling": 2,
        "instability": 0.67,
        "violations": {}
    },
    {
        "name": "App\\Controllers\\HomeController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "get",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "App\\Views\\HomeTemplate"
        ],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 0,
        "vocabulary": 0,
        "volume": 0,
        "difficulty": 0,
        "effort": 0,
        "level": 0,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 0,
        "number_operators": 0,
        "number_operands": 0,
        "number_operators_unique": 0,
        "number_operands_unique": 0,
        "cloc": 0,
        "loc": 8,
        "lloc": 8,
        "mi": 171,
        "mIwoC": 171,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 0.5,
        "relativeSystemComplexity": 1.5,
        "totalStructuralComplexity": 1,
        "totalDataComplexity": 0.5,
        "totalSystemComplexity": 1.5,
        "package": "App\\Controllers\\",
        "pageRank": 0.01,
        "afferentCoupling": 1,
        "efferentCoupling": 1,
        "instability": 0.5,
        "violations": {}
    },
    {
        "name": "App\\Controllers\\ProductController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "get",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "apiGet",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 6,
        "ccn": 5,
        "ccnMethodMax": 3,
        "externals": [
            "App\\Models\\Product",
            "App\\Views\\ProductTemplate",
            "App\\Models\\Product"
        ],
        "parents": [],
        "implements": [],
        "lcom": 2,
        "length": 48,
        "vocabulary": 15,
        "volume": 187.53,
        "difficulty": 7.75,
        "effort": 1453.36,
        "level": 0.13,
        "bugs": 0.06,
        "time": 81,
        "intelligentContent": 24.2,
        "number_operators": 17,
        "number_operands": 31,
        "number_operators_unique": 5,
        "number_operands_unique": 10,
        "cloc": 1,
        "loc": 28,
        "lloc": 27,
        "mi": 66.62,
        "mIwoC": 52.19,
        "commentWeight": 14.43,
        "kanDefect": 0.29,
        "relativeStructuralComplexity": 4,
        "relativeDataComplexity": 1.67,
        "relativeSystemComplexity": 5.67,
        "totalStructuralComplexity": 8,
        "totalDataComplexity": 3.33,
        "totalSystemComplexity": 11.33,
        "package": "App\\Controllers\\",
        "pageRank": 0.01,
        "afferentCoupling": 1,
        "efferentCoupling": 2,
        "instability": 0.67,
        "violations": {}
    },
    {
        "name": "App\\Controllers\\ProfileController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "requireAuth",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "get",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "apiUpdate",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "apiUploadAvatar",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "apiGet",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 6,
        "nbMethods": 6,
        "nbMethodsPrivate": 1,
        "nbMethodsPublic": 5,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 22,
        "ccn": 17,
        "ccnMethodMax": 9,
        "externals": [
            "App\\Models\\User",
            "App\\Views\\ProfileTemplate"
        ],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 226,
        "vocabulary": 64,
        "volume": 1356,
        "difficulty": 13.09,
        "effort": 17751.27,
        "level": 0.08,
        "bugs": 0.45,
        "time": 986,
        "intelligentContent": 103.58,
        "number_operators": 66,
        "number_operands": 160,
        "number_operators_unique": 9,
        "number_operands_unique": 55,
        "cloc": 29,
        "loc": 137,
        "lloc": 108,
        "mi": 64.12,
        "mIwoC": 31.42,
        "commentWeight": 32.7,
        "kanDefect": 1.2,
        "relativeStructuralComplexity": 25,
        "relativeDataComplexity": 2.17,
        "relativeSystemComplexity": 27.17,
        "totalStructuralComplexity": 150,
        "totalDataComplexity": 13,
        "totalSystemComplexity": 163,
        "package": "App\\Controllers\\",
        "pageRank": 0.01,
        "afferentCoupling": 1,
        "efferentCoupling": 2,
        "instability": 0.67,
        "violations": {}
    },
    {
        "name": "App\\Database\\Database",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "init",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getConnection",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "createConnection",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "closeConnection",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "isConnected",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 5,
        "nbMethods": 5,
        "nbMethodsPrivate": 1,
        "nbMethodsPublic": 4,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 14,
        "ccn": 10,
        "ccnMethodMax": 9,
        "externals": [
            "PDO",
            "PDO",
            "PDO",
            "RuntimeException"
        ],
        "parents": [],
        "implements": [],
        "lcom": 5,
        "length": 56,
        "vocabulary": 27,
        "volume": 266.27,
        "difficulty": 7.16,
        "effort": 1905.96,
        "level": 0.14,
        "bugs": 0.09,
        "time": 106,
        "intelligentContent": 37.2,
        "number_operators": 22,
        "number_operands": 34,
        "number_operators_unique": 8,
        "number_operands_unique": 19,
        "cloc": 15,
        "loc": 52,
        "lloc": 37,
        "mi": 84.43,
        "mIwoC": 47.46,
        "commentWeight": 36.97,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 4,
        "relativeDataComplexity": 1.07,
        "relativeSystemComplexity": 5.07,
        "totalStructuralComplexity": 20,
        "totalDataComplexity": 5.33,
        "totalSystemComplexity": 25.33,
        "package": "App\\Database\\",
        "pageRank": 0.21,
        "afferentCoupling": 4,
        "efferentCoupling": 2,
        "instability": 0.33,
        "violations": {}
    },
    {
        "name": "App\\Models\\Cart",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "getItems",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "add",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "updateQuantity",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "remove",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "clear",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getTotal",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getCount",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "save",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 8,
        "nbMethods": 8,
        "nbMethodsPrivate": 1,
        "nbMethodsPublic": 7,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 28,
        "ccn": 21,
        "ccnMethodMax": 7,
        "externals": [],
        "parents": [],
        "implements": [],
        "lcom": 8,
        "length": 132,
        "vocabulary": 26,
        "volume": 620.46,
        "difficulty": 30.07,
        "effort": 18655.11,
        "level": 0.03,
        "bugs": 0.21,
        "time": 1036,
        "intelligentContent": 20.64,
        "number_operators": 50,
        "number_operands": 82,
        "number_operators_unique": 11,
        "number_operands_unique": 15,
        "cloc": 27,
        "loc": 103,
        "lloc": 76,
        "mi": 72.22,
        "mIwoC": 36.59,
        "commentWeight": 35.63,
        "kanDefect": 1.17,
        "relativeStructuralComplexity": 9,
        "relativeDataComplexity": 3.03,
        "relativeSystemComplexity": 12.03,
        "totalStructuralComplexity": 72,
        "totalDataComplexity": 24.25,
        "totalSystemComplexity": 96.25,
        "package": "App\\Models\\",
        "pageRank": 0.04,
        "afferentCoupling": 2,
        "efferentCoupling": 0,
        "instability": 0,
        "violations": {}
    },
    {
        "name": "App\\Models\\EmailSender",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "getConfig",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "createMailer",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "sendOrderNotification",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "generateOrderEmailHtml",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "generateOrderEmailText",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getStatusText",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "testConnection",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "sendVerificationCode",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "generateVerificationEmailHtml",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "generateVerificationEmailText",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 10,
        "nbMethods": 10,
        "nbMethodsPrivate": 7,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 70,
        "ccn": 61,
        "ccnMethodMax": 18,
        "externals": [
            "App\\Models\\Logger",
            "PHPMailer\\PHPMailer\\PHPMailer",
            "PHPMailer\\PHPMailer\\PHPMailer",
            "Exception",
            "App\\Models\\Logger",
            "App\\Models\\Logger",
            "App\\Models\\Logger",
            "App\\Models\\Logger",
            "App\\Models\\Logger",
            "App\\Models\\Logger",
            "App\\Models\\Logger"
        ],
        "parents": [],
        "implements": [],
        "lcom": 10,
        "length": 590,
        "vocabulary": 141,
        "volume": 4212.34,
        "difficulty": 15.04,
        "effort": 63345.81,
        "level": 0.07,
        "bugs": 1.4,
        "time": 3519,
        "intelligentContent": 280.11,
        "number_operators": 196,
        "number_operands": 394,
        "number_operators_unique": 10,
        "number_operands_unique": 131,
        "cloc": 48,
        "loc": 325,
        "lloc": 274,
        "mi": 41.28,
        "mIwoC": 13.24,
        "commentWeight": 28.04,
        "kanDefect": 1.24,
        "relativeStructuralComplexity": 324,
        "relativeDataComplexity": 0.8,
        "relativeSystemComplexity": 324.8,
        "totalStructuralComplexity": 3240,
        "totalDataComplexity": 8,
        "totalSystemComplexity": 3248,
        "package": "App\\Models\\",
        "pageRank": 0.02,
        "afferentCoupling": 2,
        "efferentCoupling": 3,
        "instability": 0.6,
        "violations": {}
    },
    {
        "name": "App\\Models\\Logger",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "init",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "error",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "info",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getErrors",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getErrorCount",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "clear",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getLogPath",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 7,
        "nbMethods": 7,
        "nbMethodsPrivate": 1,
        "nbMethodsPublic": 6,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 20,
        "ccn": 14,
        "ccnMethodMax": 9,
        "externals": [],
        "parents": [],
        "implements": [],
        "lcom": 7,
        "length": 173,
        "vocabulary": 41,
        "volume": 926.86,
        "difficulty": 13.82,
        "effort": 12807.47,
        "level": 0.07,
        "bugs": 0.31,
        "time": 712,
        "intelligentContent": 67.08,
        "number_operators": 59,
        "number_operands": 114,
        "number_operators_unique": 8,
        "number_operands_unique": 33,
        "cloc": 27,
        "loc": 113,
        "lloc": 86,
        "mi": 69.49,
        "mIwoC": 35.14,
        "commentWeight": 34.35,
        "kanDefect": 0.94,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 2.86,
        "relativeSystemComplexity": 3.86,
        "totalStructuralComplexity": 7,
        "totalDataComplexity": 20,
        "totalSystemComplexity": 27,
        "package": "App\\Models\\",
        "pageRank": 0.04,
        "afferentCoupling": 3,
        "efferentCoupling": 0,
        "instability": 0,
        "violations": {}
    },
    {
        "name": "App\\Models\\Order",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "create",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "createJson",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getAll",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "findById",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "updateStatus",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "loadFromJson",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "saveToJson",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 8,
        "nbMethods": 8,
        "nbMethodsPrivate": 3,
        "nbMethodsPublic": 5,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 45,
        "ccn": 38,
        "ccnMethodMax": 10,
        "externals": [
            "App\\Config\\Config",
            "App\\Database\\Database"
        ],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 271,
        "vocabulary": 57,
        "volume": 1580.71,
        "difficulty": 25.2,
        "effort": 39833.97,
        "level": 0.04,
        "bugs": 0.53,
        "time": 2213,
        "intelligentContent": 62.73,
        "number_operators": 82,
        "number_operands": 189,
        "number_operators_unique": 12,
        "number_operands_unique": 45,
        "cloc": 24,
        "loc": 144,
        "lloc": 120,
        "mi": 56.69,
        "mIwoC": 27.14,
        "commentWeight": 29.56,
        "kanDefect": 1.98,
        "relativeStructuralComplexity": 144,
        "relativeDataComplexity": 1.21,
        "relativeSystemComplexity": 145.21,
        "totalStructuralComplexity": 1152,
        "totalDataComplexity": 9.69,
        "totalSystemComplexity": 1161.69,
        "package": "App\\Models\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Models\\Product",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "loadData",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "loadFromDatabase",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "loadFromJson",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "findById",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "findByCategory",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getCategories",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "search",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "create",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "update",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "delete",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 11,
        "nbMethods": 11,
        "nbMethodsPrivate": 2,
        "nbMethodsPublic": 9,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 52,
        "ccn": 42,
        "ccnMethodMax": 9,
        "externals": [
            "App\\Config\\Config",
            "App\\Database\\Database"
        ],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 297,
        "vocabulary": 49,
        "volume": 1667.57,
        "difficulty": 21.38,
        "effort": 35644.28,
        "level": 0.05,
        "bugs": 0.56,
        "time": 1980,
        "intelligentContent": 78.01,
        "number_operators": 107,
        "number_operands": 190,
        "number_operators_unique": 9,
        "number_operands_unique": 40,
        "cloc": 36,
        "loc": 188,
        "lloc": 152,
        "mi": 55.55,
        "mIwoC": 24.2,
        "commentWeight": 31.36,
        "kanDefect": 1.52,
        "relativeStructuralComplexity": 121,
        "relativeDataComplexity": 2.14,
        "relativeSystemComplexity": 123.14,
        "totalStructuralComplexity": 1331,
        "totalDataComplexity": 23.5,
        "totalSystemComplexity": 1354.5,
        "package": "App\\Models\\",
        "pageRank": 0.06,
        "afferentCoupling": 4,
        "efferentCoupling": 2,
        "instability": 0.33,
        "violations": {}
    },
    {
        "name": "App\\Models\\User",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "loadData",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "loadFromDatabase",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "loadFromJson",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "loadAdmins",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "saveData",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "findByEmail",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "findById",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "isAdmin",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "create",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "updateUnverifiedUser",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "createJson",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "verifyEmail",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "isVerified",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "regenerateVerificationCode",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "verifyPassword",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "updateProfile",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getFullProfile",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getOrders",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getAll",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 20,
        "nbMethods": 20,
        "nbMethodsPrivate": 5,
        "nbMethodsPublic": 15,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 128,
        "ccn": 109,
        "ccnMethodMax": 17,
        "externals": [
            "App\\Config\\Config",
            "App\\Database\\Database"
        ],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 933,
        "vocabulary": 107,
        "volume": 6289.79,
        "difficulty": 51.28,
        "effort": 322522.59,
        "level": 0.02,
        "bugs": 2.1,
        "time": 17918,
        "intelligentContent": 122.66,
        "number_operators": 304,
        "number_operands": 629,
        "number_operators_unique": 15,
        "number_operands_unique": 92,
        "cloc": 79,
        "loc": 516,
        "lloc": 437,
        "mi": 29.63,
        "mIwoC": 1.14,
        "commentWeight": 28.49,
        "kanDefect": 7.53,
        "relativeStructuralComplexity": 400,
        "relativeDataComplexity": 3.21,
        "relativeSystemComplexity": 403.21,
        "totalStructuralComplexity": 8000,
        "totalDataComplexity": 64.19,
        "totalSystemComplexity": 8064.19,
        "package": "App\\Models\\",
        "pageRank": 0.02,
        "afferentCoupling": 3,
        "efferentCoupling": 2,
        "instability": 0.4,
        "violations": {}
    },
    {
        "name": "App\\Router\\Router",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "route",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getRoutes",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "router",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "executeRouter",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "handleDefault",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 5,
        "nbMethods": 5,
        "nbMethodsPrivate": 3,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 73,
        "ccn": 69,
        "ccnMethodMax": 61,
        "externals": [
            "App\\Controllers\\AboutController",
            "App\\Controllers\\HomeController",
            "App\\Controllers\\ProductController",
            "App\\Controllers\\CatalogController",
            "App\\Controllers\\CartController",
            "App\\Controllers\\AuthController",
            "App\\Controllers\\AuthController",
            "App\\Controllers\\AuthController",
            "App\\Controllers\\AuthController",
            "App\\Controllers\\AdminController",
            "App\\Controllers\\ProfileController",
            "App\\Controllers\\ProductController",
            "App\\Controllers\\CartController",
            "App\\Controllers\\AuthController",
            "App\\Controllers\\AdminController",
            "App\\Controllers\\ProfileController",
            "App\\Models\\Logger",
            "route",
            "App\\Controllers\\HomeController"
        ],
        "parents": [],
        "implements": [],
        "lcom": 2,
        "length": 427,
        "vocabulary": 81,
        "volume": 2707.12,
        "difficulty": 11.96,
        "effort": 32377.11,
        "level": 0.08,
        "bugs": 0.9,
        "time": 1799,
        "intelligentContent": 226.35,
        "number_operators": 128,
        "number_operands": 299,
        "number_operators_unique": 6,
        "number_operands_unique": 75,
        "cloc": 16,
        "loc": 222,
        "lloc": 206,
        "mi": 36.41,
        "mIwoC": 16.21,
        "commentWeight": 20.2,
        "kanDefect": 2.17,
        "relativeStructuralComplexity": 2025,
        "relativeDataComplexity": 1.17,
        "relativeSystemComplexity": 2026.17,
        "totalStructuralComplexity": 10125,
        "totalDataComplexity": 5.85,
        "totalSystemComplexity": 10130.85,
        "package": "App\\Router\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 10,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Views\\AboutTemplate",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "loadTexts",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "loadBaseTexts",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getTemplate",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 3,
        "nbMethodsPrivate": 2,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 7,
        "ccn": 5,
        "ccnMethodMax": 3,
        "externals": [
            "App\\Views\\BaseTemplate"
        ],
        "parents": [
            "App\\Views\\BaseTemplate"
        ],
        "implements": [],
        "lcom": 3,
        "length": 47,
        "vocabulary": 17,
        "volume": 192.11,
        "difficulty": 5.63,
        "effort": 1080.62,
        "level": 0.18,
        "bugs": 0.06,
        "time": 60,
        "intelligentContent": 34.15,
        "number_operators": 20,
        "number_operands": 27,
        "number_operators_unique": 5,
        "number_operands_unique": 12,
        "cloc": 19,
        "loc": 54,
        "lloc": 35,
        "mi": 89.4,
        "mIwoC": 49.66,
        "commentWeight": 39.75,
        "kanDefect": 0.29,
        "relativeStructuralComplexity": 9,
        "relativeDataComplexity": 1.42,
        "relativeSystemComplexity": 10.42,
        "totalStructuralComplexity": 27,
        "totalDataComplexity": 4.25,
        "totalSystemComplexity": 31.25,
        "package": "App\\Views\\",
        "pageRank": 0.03,
        "afferentCoupling": 1,
        "efferentCoupling": 1,
        "instability": 0.5,
        "violations": {}
    },
    {
        "name": "App\\Views\\AdminTemplate",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "loadTexts",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "renderDashboard",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "renderOrders",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "renderOrdersList",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "renderUsers",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "renderLogs",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "renderCatalog",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "renderProductsList",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 8,
        "nbMethods": 8,
        "nbMethodsPrivate": 3,
        "nbMethodsPublic": 5,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 52,
        "ccn": 45,
        "ccnMethodMax": 22,
        "externals": [
            "App\\Views\\BaseTemplate"
        ],
        "parents": [
            "App\\Views\\BaseTemplate"
        ],
        "implements": [],
        "lcom": 8,
        "length": 468,
        "vocabulary": 134,
        "volume": 3306.93,
        "difficulty": 7.03,
        "effort": 23251.85,
        "level": 0.14,
        "bugs": 1.1,
        "time": 1292,
        "intelligentContent": 470.32,
        "number_operators": 168,
        "number_operands": 300,
        "number_operators_unique": 6,
        "number_operands_unique": 128,
        "cloc": 50,
        "loc": 250,
        "lloc": 200,
        "mi": 51.05,
        "mIwoC": 19.11,
        "commentWeight": 31.94,
        "kanDefect": 1.12,
        "relativeStructuralComplexity": 16,
        "relativeDataComplexity": 2.48,
        "relativeSystemComplexity": 18.48,
        "totalStructuralComplexity": 128,
        "totalDataComplexity": 19.8,
        "totalSystemComplexity": 147.8,
        "package": "App\\Views\\",
        "pageRank": 0.02,
        "afferentCoupling": 1,
        "efferentCoupling": 1,
        "instability": 0.5,
        "violations": {}
    },
    {
        "name": "App\\Views\\AuthTemplate",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "loadTexts",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "renderRegister",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "renderLogin",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "renderVerify",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 4,
        "nbMethods": 4,
        "nbMethodsPrivate": 1,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 6,
        "ccn": 3,
        "ccnMethodMax": 3,
        "externals": [
            "App\\Views\\BaseTemplate"
        ],
        "parents": [
            "App\\Views\\BaseTemplate"
        ],
        "implements": [],
        "lcom": 4,
        "length": 58,
        "vocabulary": 20,
        "volume": 250.67,
        "difficulty": 6.33,
        "effort": 1587.59,
        "level": 0.16,
        "bugs": 0.08,
        "time": 88,
        "intelligentContent": 39.58,
        "number_operators": 20,
        "number_operands": 38,
        "number_operators_unique": 5,
        "number_operands_unique": 15,
        "cloc": 21,
        "loc": 63,
        "lloc": 42,
        "mi": 86.38,
        "mIwoC": 47.39,
        "commentWeight": 38.99,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 4,
        "relativeDataComplexity": 2.17,
        "relativeSystemComplexity": 6.17,
        "totalStructuralComplexity": 16,
        "totalDataComplexity": 8.67,
        "totalSystemComplexity": 24.67,
        "package": "App\\Views\\",
        "pageRank": 0.02,
        "afferentCoupling": 1,
        "efferentCoupling": 1,
        "instability": 0.5,
        "violations": {}
    },
    {
        "name": "App\\Views\\BaseTemplate",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "loadTexts",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getTemplate",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 1,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 5,
        "ccn": 4,
        "ccnMethodMax": 3,
        "externals": [],
        "parents": [],
        "implements": [],
        "lcom": 2,
        "length": 24,
        "vocabulary": 12,
        "volume": 86.04,
        "difficulty": 4.64,
        "effort": 399.47,
        "level": 0.22,
        "bugs": 0.03,
        "time": 22,
        "intelligentContent": 18.53,
        "number_operators": 11,
        "number_operands": 13,
        "number_operators_unique": 5,
        "number_operands_unique": 7,
        "cloc": 11,
        "loc": 35,
        "lloc": 24,
        "mi": 93.98,
        "mIwoC": 55.81,
        "commentWeight": 38.17,
        "kanDefect": 0.29,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 2,
        "relativeSystemComplexity": 3,
        "totalStructuralComplexity": 2,
        "totalDataComplexity": 4,
        "totalSystemComplexity": 6,
        "package": "App\\Views\\",
        "pageRank": 0.23,
        "afferentCoupling": 8,
        "efferentCoupling": 0,
        "instability": 0,
        "violations": {}
    },
    {
        "name": "App\\Views\\CartTemplate",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "loadTexts",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "render",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "renderCartContent",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 3,
        "nbMethodsPrivate": 2,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 7,
        "ccn": 5,
        "ccnMethodMax": 3,
        "externals": [
            "App\\Views\\BaseTemplate",
            "App\\Models\\Cart",
            "App\\Models\\Cart",
            "App\\Models\\Cart"
        ],
        "parents": [
            "App\\Views\\BaseTemplate"
        ],
        "implements": [],
        "lcom": 3,
        "length": 148,
        "vocabulary": 48,
        "volume": 826.57,
        "difficulty": 8.11,
        "effort": 6703.32,
        "level": 0.12,
        "bugs": 0.28,
        "time": 372,
        "intelligentContent": 101.92,
        "number_operators": 53,
        "number_operands": 95,
        "number_operators_unique": 7,
        "number_operands_unique": 41,
        "cloc": 12,
        "loc": 88,
        "lloc": 76,
        "mi": 64.94,
        "mIwoC": 37.87,
        "commentWeight": 27.07,
        "kanDefect": 0.52,
        "relativeStructuralComplexity": 36,
        "relativeDataComplexity": 0.76,
        "relativeSystemComplexity": 36.76,
        "totalStructuralComplexity": 108,
        "totalDataComplexity": 2.29,
        "totalSystemComplexity": 110.29,
        "package": "App\\Views\\",
        "pageRank": 0.01,
        "afferentCoupling": 1,
        "efferentCoupling": 2,
        "instability": 0.67,
        "violations": {}
    },
    {
        "name": "App\\Views\\CatalogTemplate",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "loadTexts",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getTemplate",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "render",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "renderProductsGrid",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "renderEmptyState",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "renderSearchInfo",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 6,
        "nbMethods": 6,
        "nbMethodsPrivate": 4,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 31,
        "ccn": 26,
        "ccnMethodMax": 16,
        "externals": [
            "App\\Views\\BaseTemplate"
        ],
        "parents": [
            "App\\Views\\BaseTemplate"
        ],
        "implements": [],
        "lcom": 6,
        "length": 270,
        "vocabulary": 85,
        "volume": 1730.54,
        "difficulty": 7.63,
        "effort": 13200.88,
        "level": 0.13,
        "bugs": 0.58,
        "time": 733,
        "intelligentContent": 226.86,
        "number_operators": 100,
        "number_operands": 170,
        "number_operators_unique": 7,
        "number_operands_unique": 78,
        "cloc": 31,
        "loc": 144,
        "lloc": 113,
        "mi": 61.97,
        "mIwoC": 29.04,
        "commentWeight": 32.92,
        "kanDefect": 0.59,
        "relativeStructuralComplexity": 36,
        "relativeDataComplexity": 1.52,
        "relativeSystemComplexity": 37.52,
        "totalStructuralComplexity": 216,
        "totalDataComplexity": 9.14,
        "totalSystemComplexity": 225.14,
        "package": "App\\Views\\",
        "pageRank": 0.02,
        "afferentCoupling": 1,
        "efferentCoupling": 1,
        "instability": 0.5,
        "violations": {}
    },
    {
        "name": "App\\Views\\HomeTemplate",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "loadTexts",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getTemplate",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "renderProducts",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 3,
        "nbMethodsPrivate": 2,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 17,
        "ccn": 15,
        "ccnMethodMax": 12,
        "externals": [
            "App\\Views\\BaseTemplate",
            "App\\Models\\Product"
        ],
        "parents": [
            "App\\Views\\BaseTemplate"
        ],
        "implements": [],
        "lcom": 3,
        "length": 159,
        "vocabulary": 53,
        "volume": 910.74,
        "difficulty": 6.38,
        "effort": 5813.23,
        "level": 0.16,
        "bugs": 0.3,
        "time": 323,
        "intelligentContent": 142.68,
        "number_operators": 59,
        "number_operands": 100,
        "number_operators_unique": 6,
        "number_operands_unique": 47,
        "cloc": 18,
        "loc": 84,
        "lloc": 66,
        "mi": 70.43,
        "mIwoC": 37.57,
        "commentWeight": 32.86,
        "kanDefect": 0.52,
        "relativeStructuralComplexity": 16,
        "relativeDataComplexity": 1.27,
        "relativeSystemComplexity": 17.27,
        "totalStructuralComplexity": 48,
        "totalDataComplexity": 3.8,
        "totalSystemComplexity": 51.8,
        "package": "App\\Views\\",
        "pageRank": 0.03,
        "afferentCoupling": 1,
        "efferentCoupling": 2,
        "instability": 0.67,
        "violations": {}
    },
    {
        "name": "App\\Views\\ProductTemplate",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "loadTexts",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getCardTemplate",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 1,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 12,
        "ccn": 11,
        "ccnMethodMax": 9,
        "externals": [
            "App\\Views\\BaseTemplate"
        ],
        "parents": [
            "App\\Views\\BaseTemplate"
        ],
        "implements": [],
        "lcom": 2,
        "length": 113,
        "vocabulary": 33,
        "volume": 570.02,
        "difficulty": 6.88,
        "effort": 3918.86,
        "level": 0.15,
        "bugs": 0.19,
        "time": 218,
        "intelligentContent": 82.91,
        "number_operators": 36,
        "number_operands": 77,
        "number_operators_unique": 5,
        "number_operands_unique": 28,
        "cloc": 13,
        "loc": 57,
        "lloc": 44,
        "mi": 77.08,
        "mIwoC": 43.37,
        "commentWeight": 33.71,
        "kanDefect": 0.29,
        "relativeStructuralComplexity": 4,
        "relativeDataComplexity": 1.17,
        "relativeSystemComplexity": 5.17,
        "totalStructuralComplexity": 8,
        "totalDataComplexity": 2.33,
        "totalSystemComplexity": 10.33,
        "package": "App\\Views\\",
        "pageRank": 0.02,
        "afferentCoupling": 1,
        "efferentCoupling": 1,
        "instability": 0.5,
        "violations": {}
    },
    {
        "name": "App\\Views\\ProfileTemplate",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "loadTexts",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "render",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 1,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 58,
        "ccn": 57,
        "ccnMethodMax": 56,
        "externals": [
            "App\\Views\\BaseTemplate"
        ],
        "parents": [
            "App\\Views\\BaseTemplate"
        ],
        "implements": [],
        "lcom": 2,
        "length": 522,
        "vocabulary": 167,
        "volume": 3854.29,
        "difficulty": 9.01,
        "effort": 34712.88,
        "level": 0.11,
        "bugs": 1.28,
        "time": 1928,
        "intelligentContent": 427.96,
        "number_operators": 164,
        "number_operands": 358,
        "number_operators_unique": 8,
        "number_operands_unique": 159,
        "cloc": 17,
        "loc": 281,
        "lloc": 251,
        "mi": 33.47,
        "mIwoC": 14.88,
        "commentWeight": 18.59,
        "kanDefect": 0.89,
        "relativeStructuralComplexity": 4,
        "relativeDataComplexity": 1,
        "relativeSystemComplexity": 5,
        "totalStructuralComplexity": 8,
        "totalDataComplexity": 2,
        "totalSystemComplexity": 10,
        "package": "App\\Views\\",
        "pageRank": 0.02,
        "afferentCoupling": 1,
        "efferentCoupling": 1,
        "instability": 0.5,
        "violations": {}
    }
]